{
 "title": "COVID19 v CR - zakladni statistiky BETA",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1d,7d,14d,30d" },
   { "name": "obyvatel", "query": "10701777" },
   { "name": "obyvatel65", "query": "2158322" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Nesnažíme se duplikovat existující snahy vizualizovat dostupná data o průběhu pandemie v ČR. Naší motivací je vytvořit rozhraní, které umožní větší interaktivitu vizualizací a tím v důsledku snazší interpretaci dat. Zároveň se snažíme o co největší transparentnost ohledně toho, jak se které grafy a křivky počítají, aby bylo možné grafy na základě Vaší zpětné vazby dále zlepšovat (s náměty piště na covid@nubim.cz).  \n\n    Umístěním kurzoru na \"i\" v levém horním rohu grafu zobrazíte informace o daném grafu.\n    Kliknutím na proměnnou v legendě grafu je zobrazena pouze jedna proměnná.\n    Zoom - Kliknutím a potažením po grafu lze vybrat část grafu ke zvětšení.\n    Přejetím myší po grafu se zobrazí legenda s konkrétními čísly v grafu.\n    Kliknutím na hodiny v pravém horním rohu okna lze změnit sledované období - rozšířit nebo zkrátit.\n    Kliknutím na \"interval\" v levém horním rohu okna lze vybrat sedmidenní průměr který vyhladí špičky vzniklé rozdíly v měření v jednotlivých dnech v týdnu (např. v neděli se testuje méně). Vhodné pro sledování trendů.\n\n[poslední rok](https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&from=now-1y&to=now) |\n[posledních 90dní](https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&from=now-90d&to=now) |\n[poslední měsíc](https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&from=now-30d&to=now) |\nVíce na www.blog.nubium.cz/covidova-grafana/"
   }
  },
  { "title": "kontrolni data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "základní přehled", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "prehled mysql (melo by vychazet stejne jako json)",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  potvrzene_pripady_celkem AS \"pripady celkem\",\n  aktivni_pripady AS \"aktivni pripady\",\n  umrti AS \"umrti\",\n  aktualne_hospitalizovani AS \"aktualne hospitalizovani\",\n  potvrzene_pripady_vcerejsi_den AS \"nakazy dnes\",\n  potvrzene_pripady_65_vcerejsi_den AS \"nakazy 65+\",\n  vykazana_ockovani_vcerejsi_den AS \"ockovani dnes\"\nFROM zakladni_prehled\nWHERE\n  datum = (select max(datum) from zakladni_prehled);\n  \n# select max(pocet_davek_kumulativne) as `ockovanych celkem` from ockovani_ukoncena;\n# select 10701777-max(pocet_davek_kumulativne) as `neockovanych celkem` from ockovani_ukoncena;\n# select round(incidence_pozitivni/pocet_PCR_testy*100,1) as `pozitivnich PCR testu %` from testy_pcr_antigenni WHERE datum = (select max(datum) from testy_pcr_antigenni);",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  potvrzene_pripady_celkem AS \"pripady celkem\",\n  aktivni_pripady AS \"aktivni pripady\",\n  umrti AS \"umrti\",\n  aktualne_hospitalizovani AS \"aktualne hospitalizovani\",\n  potvrzene_pripady_vcerejsi_den AS \"nakazy dnes\",\n  potvrzene_pripady_65_vcerejsi_den AS \"nakazy 65+\",\n  vykazana_ockovani_vcerejsi_den AS \"ockovani dnes\"\nFROM zakladni_prehled\nWHERE\n  datum = (select max(datum) from zakladni_prehled);\n  \n# select max(pocet_davek_kumulativne) as `ockovanych celkem` from ockovani_ukoncena;\n# select 10701777-max(pocet_davek_kumulativne) as `neockovanych celkem` from ockovani_ukoncena;\n# select round(incidence_pozitivni/pocet_PCR_testy*100,1) as `pozitivnich PCR testu %` from testy_pcr_antigenni WHERE datum = (select max(datum) from testy_pcr_antigenni);",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "grafy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Denní přehled počtu osob s nově prokázaným onemocněním COVID‑19",
   "type": "timeseries",
   "description": "Denní přehled počtu osob s pozitivním nálezem COVID‑19 dle hlášení KHS a dle pozitivních nálezů laboratoří, které jsou určeny pro další šetření.\n\nS ohledem na fakt, že u publikovaných dat probíhá validace a průběžné doplňování hlášení, může u přehledů osob s laboratorně prokázaným onemocněním COVID‑19 dle hlášení KHS a laboratoří docházet zpětně k drobným změnám. Poslední aktualizace dat v tomto přehledu byla provedena k půlnoci předchozího dne.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(prirustkovy_pocet_nakazenych) AS \"přířůstkový počet nakažených\"\nFROM nakazeni_vyleceni_umrti_testy\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Denní počty ukončených očkování",
   "type": "timeseries",
   "description": "Denní počty očkovaných druhou dávkou nebo první u jednodávkové vakcíny (Janssen). Graf nezohledňuje třetí posilující dávky.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_davek) AS \"ukončená očkování\"\nFROM ockovani_ukoncena\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Denní počty očkovaných podle dávky",
   "type": "timeseries",
   "description": "Dává přehled pouze o aktuálně vykázaných dávkách očkování, nikoliv o imunitě.\n\nPříklad interpretace grafu: V červnu 2021 byla vysoká vytíženost očkovacích míst.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_davek) AS \"první dávka\"\nFROM ockovani_prvnidavka\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_davek) AS \"druhá dávka\"\nFROM ockovani_druhadavka\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_davek) AS \"třetí dávka\"\nFROM ockovani_tretidavka\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Odhad aktuálního počtu lidí v populaci s aktivní imunitou získanou očkováním",
   "type": "timeseries",
   "description": "Odhad aktuálního počtu lidí v populaci s aktivní imunitou získanou očkováním.\n\nZahrnuje lidi kteří mají:\n- dvě dávky nebo jednu dávku u jednodávkových vakcín (Janssen) = ukončené základní očkování\n- a zároveň buď neuplynulo od očkování 6 měsíců nebo 6 měsíců uplynulo a již dostali posilující dávku\n\nOdhad nezohledňuje zpoždění 14 dní od očkování než je imunita plně aktivní.\n\nPříklad interpretace grafu: V grafu můžeme sledovat pokles počtu očkovaných s aktivní imunitou v říjnu 2021, která je daná uběhnutím 6 měsíců od ukončeného základního očkování u části očkovaných, kterým ale nebyla administrována posilující dávka.\n\nRozpad na konkrétní křivky, které byly použité pro výpočet tohoto výsledného grafu najdete níže nebo na přímém odkazu <a href=\"https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&viewPanel=43\">zde</a>.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(ockovanych_kumulativne-expirujici_davky_kumulativne+ockovanych_tretidavka_kumulativne) AS \"očkovaní s aktivní imunitou\"\n  FROM ockovani_expirace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Odhad aktuálního počtu lidí v populaci s aktivní imunitou získanou očkováním - rozpad",
   "type": "timeseries",
   "description": "Graf poskytuje vhled do výpočtu očkovaných s aktivní imunitou (viz graf výše).\n\n- Očkovaní s druhou dávkou = kumulativní počty lidí s ukončeným základním očkováním (dvě dávky nebo jedna dávka u jednodávkových vakcín)\n- Očkovaní s posilující dávkou = kumulativní počty lidí s ukončeným základním očkováním kterým uplynula 6 měsíční lhůta, po které šli na posilující dávku\n- Očkovaní druhou dávkou před více než 6 měsíci = kumulativní počty lidí s ukončeným základním očkováním kterým uplynula 6 měsíční lhůta (bez ohledu na to jestli byli na posilující dávce nebo ne)\n- Očkovaní s aktivní imunitou = \"Očkovaní s druhou dávkou\" - \"Očkovaní druhou dávkou před více než 6 měsíci\" + \"Očkovaní s posilující dávkou\"\n- Očkovaní kterým chybí posilující dávka = \"Očkovaní druhou dávkou před více než 6 měsíci\" - \"Očkovaní s posilující dávkou\"\n\nPříklad interpretace grafu: V grafu můžeme sledovat pokles počtu očkovaných s aktivní imunitou v říjnu 2021, která je daná uběhnutím 6 měsíců od ukončeného základního očkování u části očkovaných, kterým ale nebyla administrována posilující dávka.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(ockovanych_kumulativne) AS \"očkovaní s druhou dávkou\",\n  avg(ockovanych_tretidavka_kumulativne) AS \"očkovaní s posilující dávkou\",\n  avg(expirujici_davky_kumulativne) AS \"očkovaní druhou dávkou před více než 6 měsíci\",\n  avg(ockovanych_kumulativne-expirujici_davky_kumulativne+ockovanych_tretidavka_kumulativne) AS \"očkovaní s aktivní imunitou\",\n  avg(expirujici_davky_kumulativne-ockovanych_tretidavka_kumulativne) AS \"očkovaní kterým chybí posilující dávka\"\nFROM ockovani_expirace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Poměr očkovaných v populaci v %",
   "type": "timeseries",
   "description": "Graf s křivkami identickými z grafu <a href=\"https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&viewPanel=43\">Odhad aktuálního počtu lidí v populaci s aktivní imunitou získanou očkováním - rozpad</a> s tím rozdílem, že nepoužívá absolutní čísla, ale procento populace ČR. Populace ČR je definována 10701777 obyvatel dle <a href=\"https://www.czso.cz/csu/czso/pocet-obyvatel-v-obcich-k-112021\">odhadů ČSÚ k  1. 1. 2021</a>.\n\nOčkovaní = kumulativní počty lidí s ukončeným základním očkováním (dvě dávky nebo jedna dávka u jednodávkových vakcín), nebere v úvahu nutnost posilujících vakcín\nOčkovaní s aktivní imunitou = Odhad aktuálního počtu lidí v populaci s aktivní imunitou získanou očkováním, podrobnosti viz grafy výše \n\nAktuální číslo je užitečné hlavně při porovnávání jednotlivých zemí; od konkrétního čísla jakožto cíle pro získání kolektivní imunity se upustilo, protože kolektivní imunita nemusí být možná a tudíž se apeluje na co možná nejvyšší proočkovanost, viz např. <a href=\"https://www.meses.cz/stanovisko-k-ockovani-proti-nemoci-covid-19/\">zde</a>.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_davek_kumulativne/$obyvatel*100) AS \"očkovaní\"\nFROM ockovani_ukoncena\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg((ockovanych_kumulativne-expirujici_davky_kumulativne+ockovanych_tretidavka_kumulativne)/$obyvatel*100) AS \"očkovaní s aktivní imunitou\"\nFROM ockovani_expirace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Odhad aktuálního počtu lidí v populaci s imunitou získanou proděláním nemocí (6 měsíců)",
   "type": "timeseries",
   "description": "Odhad aktuálního počtu lidí v populaci s imunitou získanou proděláním nemocí. Graf vychází z reportovaného počtu vyléčených případů a zohledňuje slábnutí imunity v čase. Slábnutí imunity po prodělání nemoci je dost individuální ale pro účely odhadu používáme konzervativních 6 měsíců. Reportovaní vyléčení jsou tedy přidáváni do počtu imunních a po 6 měsících jsou z tohoto součtu odebráni. Rozpad na konkrétní křivky, které byly použité pro výpočet tohoto výsledného grafu najdete níže nebo na přímém odkazu <a href=\"https://covid.nubium.cz/d/ygM9GvKnz/covid19-v-cr-zakladni-statistiky-beta?orgId=1&viewPanel=44\">zde</a>.\n\nPodroběji viz:\nhttps://www.meses.cz/stanovisko-meses-k-vyvoji-epidemie-covid-19-v-podzimnich-mesicich-2021/\nhttps://www.ecdc.europa.eu/en/covid-19/latest-evidence/immune-responses\n\n\nPříklad interpretace grafu: V létě 2021 bylo v populaci poměrně silné zastoupení imunních z prodělání nemoci v rámci podzim 2020 - jaro 2021 vlny covidu. Tato imunita se nicméně vytrácí koncem října 2021.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(vylecenych_kumulativne-expirujici_promoreni_kumulativne) AS \"aktivní imunita z prodělání nemoci\"\nFROM promoreni_expirace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Odhad aktuálního počtu lidí v populaci s imunitou získanou proděláním nemocí (6 měsíců)",
   "type": "timeseries",
   "description": "Odhad aktuálního počtu lidí v populaci s imunitou získanou proděláním nemocí. Graf vychází z reportovaného počtu vyléčených případů a zohledňuje slábnutí imunity v čase. Slábnutí imunity po prodělání nemoci je dost individuální ale pro účely odhadu používáme konzervativních 6 měsíců. \n\n\nPodroběji viz:\nhttps://www.meses.cz/stanovisko-meses-k-vyvoji-epidemie-covid-19-v-podzimnich-mesicich-2021/\nhttps://www.ecdc.europa.eu/en/covid-19/latest-evidence/immune-responses\n\n- s prodělanou nemocí = kumulativní počet reportovaných vyléčených\n- 6 měsíců po prodělané nemoci = \"s prodělanou nemocí\" + 6 měsíců\n- aktivní imunita z prodělání nemoci = \"s prodělanou nemocí\" - \"6 měsíců po prodělané nemoci\"\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(vylecenych_kumulativne) AS \"s prodělanou nemocí\",\n  avg(expirujici_promoreni_kumulativne) AS \"6 měsíců po prodělání nemoci\",\n  avg(vylecenych_kumulativne-expirujici_promoreni_kumulativne) AS \"aktivní imunita z prodělání nemoci\"\nFROM promoreni_expirace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": " Přehled hospitalizací podle příznaků",
   "type": "timeseries",
   "description": "aditivne podle https://www.seznamzpravy.cz/clanek/koronavirus-pocet-hospitalizovanych-120161 a  https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(stav_bez_priznaku) AS \"bez příznaků\",\n  avg(stav_lehky) AS \"lehký\",\n  avg(stav_stredni) AS \"střední\",\n  avg(stav_tezky) AS \"těžký\"\nFROM hospitalizace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_hosp) AS \"celkem\"\nFROM hospitalizace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)"
    }
   ]
  },
  {
   "title": "Přehled hospitalizací podle podpůrných přístrojů",
   "type": "timeseries",
   "description": "aditivne podle https://www.seznamzpravy.cz/clanek/koronavirus-pocet-hospitalizovanych-120161",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(jip) AS \"JIP\",\n  avg(kyslik) AS \"kyslík\",\n  avg(hfno) AS \"HFNO\",\n  avg(upv) AS \"UPV\",\n  avg(ecmo) AS \"ECMO\",\n  avg(tezky_upv_ecmo) AS \"těžký UPV a ECMO\"\nFROM hospitalizace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Přehled provedených testů",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_PCR_testy) AS \"PCR testy\",\n  avg(pocet_AG_testy) AS \"AG testy\"\nFROM testy_pcr_antigenni\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Pozitivita PCR testů",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pocet_PCR_testy) AS \"pocet_PCR_testy\",\n  avg(incidence_pozitivni) AS \"incidence_pozitivni\"\nFROM testy_pcr_antigenni\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Očkování",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 131 },
   "options": {
    "content": "nasledujici nefunguje protoze ye potreba koukat na struturu\n\nviz odkaz na https://ockovani.opendatalab.cz/statistiky\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datum AS \"time\",\n  pacient_prvni_zaznam\nFROM hospitalizace\nWHERE\n  $__timeFilter(datum)\nORDER BY datum"
    }
   ]
  },
  {
   "title": "Přehled osob s prokázanou nákazou s ohledem na vykázaná očkování",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(pozitivni_bez_ockovani) AS \"pozitivní  bez očkování\",\n  avg(pozitivni_dokoncene_ockovani) AS \"pozitivní s dokončeným očkováním\",\n  avg(pozitivni_posilujici_davka) AS \"pozitivní s posilující dávkou\"\nFROM ockovani_pozitivni\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Přehled hospitalizací s ohledem na vykázaná očkování",
   "type": "timeseries",
   "description": "\nzdroj: https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(hospitalizovani_bez_ockovani) AS \"hospitalizovaní bez očkování\",\n  avg(hospitalizovani_nedokoncene_ockovani) AS \"hospitalizovaní s nedokončeným očkováním\",\n  avg(hospitalizovani_dokoncene_ockovani) AS \"hospitalizovaní s dokončeným očkováním\",\n  avg(hospitalizovani_posilujici_davka) AS \"hospitalizovaní s posilující dávkou\"\nFROM ockovani_hospitalizace\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Úmrtí",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(umrti_bez_ockovani) AS \"neočkovaní\",\n  avg(umrti_dokoncene_ockovani) AS \"dokončené očkování\",\n  avg(umrti_nedokoncene_ockovani) AS \"nedokončené očkování\"\nFROM ockovani_umrti\nWHERE\n  $__timeFilter(datum)\nGROUP BY 1\nORDER BY $__timeGroup(datum,$__interval)",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 161 },
   "options": {
    "content": "zdroj dat: UZIS a Statisticky urad. Data jsou  aktualizována každou hodinu, UZIS publikuje datové sady z předchozího dne mezi 6 a 8 hodinou ranní.\n\njakekoliv komentáře, nápady či připomínky pište na covid@nubium.cz\n\nNástroj Grafana používáme pro monitoring a grafovani parametrů provozovaných služeb v Nubium Development SE, chceš li více o naší praci, podívejte se na www.nubium.jobs.\n\n&copy; 2021 Nubium Development SE, licence [CC BY-SA](www.creativecommons.org/licenses/). Zdrojove kody grafů pod AGPL licenci na www.github.com/nubium/. Nástroj grafana lze získat zdarma na www.grafana.com."
   }
  }
 ]
}